### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [gabriel-pinheiro/datapacks#8]

**Comment by gabriel-pinheiro** [comment]
Hey @sternschnaube ! I plan to upgrade it to 1.21 this weekend, thanks for the suggestion 😄

**Comment by sternschnaube** [comment]
Thank you both very much!
Any update @gabriel-pinheiro? 😊

**Comment by zboggert** [comment]
Although more might be added in the official update, you can get the datapack working in 1.21 by going through every file in the datapack and changing the "loot tables", "predicates", and "functions" to their respective singular form (loot table, predicate, and function) this should be enough to get it working and it's essentially what I fixed in the file I uploaded.

**Comment by gabriel-pinheiro** [comment]
Hey @sternschnaube ! The new version is finally out 😄 

You can download Warp Portals v1.4.0 from the link below. It supports all Minecraft versions from 1.18 to 1.21:
https://modrinth.com/datapack/warp-portals/changelog

Thank you so much for the contribution @zboggert ! Those are really most of the changes, for the official release it had to be done a bit differently to ensure compatibility with older Minecraft versions (the changes were made in new overlays, merging the older ones accordingly). Feel free to check out the repo 😄 

Let me know if it works, and I'll close the issue!
